server:
  port: 8095

spring:
  application:
    name: order-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: trackflow

    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    admin:
      fail-fast: false